<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<title>htm Demo</title>
<script type="module">
  import { html, render, Component } from 'https://esm.sh/htm/preact/standalone'
  import { HeaderMenu } from "/app/sae/design/desktop/backoffice/js/next/components/header-menu.js"

  class App extends Component {
    lastIndex = 0;

    addTodo() {
      const {todos = []} = this.state;
      this.setState({todos: todos.concat(`Item n.${++this.lastIndex}`)});
    }

    removeTodo(item) {
      return () => {
        const {todos = []} = this.state;
        this.setState({todos: todos.filter(todo => todo !== item)});
      }
    }

    render({page}, {todos = []}) {
      return html`
        <${HeaderMenu}/>
        <div class="app">

          <${Header} name="ToDo's (${page})"/>
          <button onClick=${() => this.addTodo()}>Add Todo</button>
          <ul>
            ${todos.map(todo => html`
              <li key=${todo} onClick=${this.removeTodo(todo)}>${todo}</li>
            `)}
          </ul>

          <${Footer}>footer content here<//>
        </div>
      `;
    }
  }

  const Header = ({name}) => html`<h1>${name} List</h1>`

  const Footer = props => html`
    <footer ...${props}/>`

  render(html`
    <${App} page="All"/>`, document.getElementById('root-container'));
</script>
<body class="bg-gray-100">
<div id="root-container" class="container md:mx-auto border-2 border-orange-400 bg-white rounded shadow-lg my-4 p-4">

</div>
</body>
</html>